# Generated by Django 3.0.4 on 2020-04-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('pages', models.PositiveIntegerField()),
                ('format', models.CharField(max_length=64)),
                ('publish_year', models.PositiveIntegerField()),
            ],
        ),
    ]
